name: Ubuntu Docker with Remote Desktop

on:
  push:
    branches:
      - main

jobs:
  setup-ubuntu-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.5.3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.0

      - name: Build and run Docker image
        run: |
          docker build -t ubuntu-remote-desktop .
          docker run -p 3389:3389 ubuntu-remote-desktop
